apiVersion: batch/v1
kind: Job
metadata:
  name: before-test
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: test-job
        image: alpine:latest
        command: ["sleep", "1000"]
      restartPolicy: Never
  backoffLimit: 0