apiVersion: batch/v1
kind: Job
metadata:
  generateName: helm-job-test-
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-2"
spec:
  template:
    spec:
      containers:
        - name: test-job
          image: alpine:latest
          command: ["ls"]
      restartPolicy: Never
